### PR TITLE
related #54

### PR DESCRIPTION
**Pull request by ygokirmak**
- Upgraded to official ELK 5.3 images
 - Instead of loading dashboards within Dockerfile of jhipster-console, short-lived (jhipster-import-dashboards) docker container is used.
 - It is observed that kibana requires at least one document to create logstash-* index and render screens properly. Without index there is a blank screen problem. Bec of that one more short-lived container used for importing sample document.

@PierreBesson; jhipster-import-data and jhipster-import-dashboards containers should wait till elasticsearch and logstash  containers are up. Because `depends_on: {elasticsearch: {condition: service_healthy}}` capability is not supported on docker-compose file version 2, we can use https://github.com/jwilder/dockerize to wait till services up.. 

Can u review and give feedback for the PR?

### CODE REVIEW

**Comment by PierreBesson** [comment]
This is awesome ! Just give me some time to review it.

**Comment by PierreBesson** [comment]
This is looking quite fine, but it needs more env variables rather than hard coded values, especially for the hostnames like (jhipster-logstash). This is because when deploying without something else than docker-compose it can be adapted to the environment.

I would also like to have env vars for the login credentials, with the defaults being admin/admin.

**Comment by ygokirmak** [comment]
Ok I will add env variables and inform you @PierreBesson 
for the login credentials.. bec I disabled xpack actually we don't need any login credentials; do you agree?

**Comment by PierreBesson** [comment]
Yes I agree security is outside of the scope of the console for now.

**Comment by ygokirmak** [comment]
@PierreBesson commited change for env variable.. check please

**Comment by PierreBesson** [comment]
I'm in vacation currently. Sorry that reviewing this is taking a long time.

**Comment by PierreBesson** [comment]
@ygokirmak I'm back from vacation. I'm going to merge your PR soon, then I will do some modifications as we cannot depends on volumes for initial setup all the time. The default dashboards need to be shipped with the docker images. This is for demo purpose so it can works when volumes are not available like in Kubernetes, Rancher or Swarm.
However I really like your approach as your are using the official import dashboards scripts (those actually didn't exist back then).

**Pull request merged**
