### PR TITLE
added Elasticsearch Curator

### PR DESCRIPTION
**Pull request by anjia0532**
[Elasticsearch Curator](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/about.html) helps you curate, or manage, your Elasticsearch indices and snapshots by:

Obtaining the full list of indices (or snapshots) from the cluster, as the actionable list
Iterate through a list of user-defined filters to progressively remove indices (or snapshots) from this actionable list as needed.
Perform various actions on the items which remain in the actionable list.

### CODE REVIEW

**Comment by jdubois** [comment]
Sorry to be the bad guy here, but for me our "monitoring" stack is already getting way too big. Since @PierreBesson added Zipkin, I now need 12Go of RAM to do my usual demo (compared to 8Go previously), so I'm afraid of having something that gets too bloated (even if that adds lots of new features).
@PierreBesson could we have Curator (and Zipkin!) as options instead? It could be another question in the docker-compose sub-generator

**Comment by anjia0532** [comment]
@jdubois the curator and alerter default is closed. [docker-compose.yml#L42-L55](https://github.com/anjia0532/jhipster-console/blob/67e1ca3080367cc7f7c7b5f84371d3d377ab8c67/docker-compose.yml#L42-L55)

**Comment by PierreBesson** [comment]
@anjia0532 This rocks !
@jdubois of course this new feature would be an option, it is only needed for cleaning old logs in a production elasticsearch.
You are right to say that the console is very big. I will change the docker sub-gen so that you can choose one or several of these options:
- ELK
- Zipkin
- Elastalert (not currently in the subgen)
- Curator (not currently in the subgen)
- Prometheus (with grafana)
Also I think we should rename the jhipster-console into jhipster-kibana. This is a bit silly to try to rebrand it as ours.

**Comment by jdubois** [comment]
@PierreBesson +1 for the options, to have something smaller
For the name: we don't have the right to use "Kibana", it must be protected by Elastic, and the Apache 2 license

**Comment by deepu105** [comment]
Since we provide consoole as a wrapper with other features pre configured I think its ok to keep the name as jhipster-console

**Comment by PierreBesson** [comment]
@anjia0532 I have not forgotten you, I will review this PR when I have the time.

**Comment by anjia0532** [comment]
@PierreBesson ok , : )

**Comment by ruddell** [comment]
This is working well in my JHipster Console, thanks!  Disk space was the main reason I stopped using the Console a while ago, and this solves that issue.

One thing to note is that the indexes are created each `day`, so that's the smallest unit you can use with the Curator

**Comment by anjia0532** [comment]
@ruddell the curator is powerful . 

[Curator Reference [5.1] » Filter Elements » unit](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/fe_unit.html) ,the smallest unit is seconds . 

[Curator Reference [5.1] » Filters](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/filters.html) it support index's filtertypes are : `age,alias,allocated,closed,count,forcemerged,kibana,none,opened,pattern,period,space` and the snapshot filtertypes are : age,count,none,pattern,period,state

**Comment by PierreBesson** [comment]
@ruddell Cool, then I will merge this and try to integrate it in the kubernetes, rancher and openshift subgen so that it is set up automatically for users.

**Pull request merged**
