### PR TITLE
[WIP] Use Curator to close old indices and improve performance

### PR DESCRIPTION
**Pull request by gmarziou**
Add supervisor to Docker container to be able to run both cron and elasticsearch.
Cron is used to run Curator daily to close indices older then 30 days.

### CODE REVIEW

**Comment by gmarziou** [comment]
Hi @PierreBesson, please don't merge there is a problem with ES 5.0. while it was working perfectly with ES 2.4.0

It could be due to supervisord or maybe some missing comma
nd line option, I'll investigate, ES stops almost immediately with exit code 78 and then supervisord restarts it  (because of `autorestart=true`) and so on*;

**Comment by PierreBesson** [comment]
Thanks @gmarziou for your contribution ! I will try to test it and merge it for the 2.0.0 release.

**Comment by gmarziou** [comment]
Pierre, just to let you know that it's hard for me to work on this as I don't use Docker at work.

**Comment by PierreBesson** [comment]
@gmarziou I understand, thanks a lot anyway, I will implement this when I have the time, I will also do it as a separate container so that it can work against an elasticsearch cluster and to use it with Kubernetes.
So I'm closing this and opening an issue.

**Pull request closed without merging**
